### ISSUE TITLE
Refactor code to conform to PEP8

### ISSUE THREAD

**Issue by calum-mcg** [MrPowers/chispa#65]
Non-essential, would help to improve readability of code by ensuring the style conforms to PEP8 standards, including:

- Indentation
- Max line length
- Naming conventions
- Comments

**Comment by calum-mcg** [comment]
@MrPowers - happy to create a stab at this and put in a PR. Let me know if it would be useful

**Comment by MrPowers** [comment]
@calum-mcg - yea, can you please open a PR.  Here's my preferred setup:

* black code formatting
* CI checks to verify the code follows black (but doesn't actually modify the code)
* Ruff linting

What do you think?

**Comment by MrPowers** [comment]
Great. thank you!

**Comment by MrPowers** [comment]
I am going to do my best to either merge or close the existing PRs.  Once those are dealt with, we can format the code.  I don't want to reformat the code just yet cause that could cause some difficult conflict resolution.

**Comment by benberryallwood** [comment]
Can I suggest using `ruff` for formatting as well as linting rather than `black` - it behaves in pretty much the same way but is much faster and would reduce the number of dependencies.

Also, if the formatting is done in its own PR then resolving those conflicts would just be taking the other branch's changes and running the formatting on them. So maybe separating the formatting from the other changes mentioned here could help speed things up.
